- name: DB_PASSWORD
  value: "Secret123456"
  description: Password for the database
## Optional parameters: if you want to use optional parameters, please uncomment the following lines
#- name: AZURE_OPENAI_KEY
#  value: ""
#  description: [Optional] OpenAI key
#- name: AZURE_OPENAI_ENDPOINT
#  value: ""
#  description: [Optional] OpenAI endpoint
#- name: AZURE_OPENAI_DEPLOYMENT_NAME
#  value: ""
#  description: [Optional] OpenAI deployment name
#- name: MSTEAMS_WEBHOOK
#  value: ""
#  description: [Optional] Web hook for Microsoft Teams channel

