apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: ${project.artifactId}-cluster
  namespace: ${param.namespace}
spec:
  replicas: ${param.replicas}
  applicationImage: ${param.login.server}/${project.artifactId}:${project.version}
  pullPolicy: Always
  service:
    type: ClusterIP
    port: 9080
  env:
    - name: DB_SERVER_NAME
      valueFrom:
        secretKeyRef:
          name: db-secret-sql
          key: db.server.name
    - name: DB_PORT_NUMBER
      valueFrom:
        secretKeyRef:
          name: db-secret-sql
          key: db.port.number
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: db-secret-sql
          key: db.name
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret-sql
          key: db.user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret-sql
          key: db.password
    - name: APPLICATIONINSIGHTS_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: app-insight-secret
          key: connection.string
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${project.artifactId}-ingress
  namespace: default
  annotations:
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/use-private-ip: "false"
spec:
  ingressClassName: azure-application-gateway
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${project.artifactId}-cluster
                port:
                  number: 9080
